### ISSUE TITLE
please re enable the plasma studio functionality in the package

### ISSUE THREAD

**Issue by fisforfaheem** [felixblaschke/simple_animations#101]
it was amaing just see the usage of this video https://youtu.be/LbrGzPEFVNs

**Comment by felixblaschke** [comment]
Hey I made the code for liquid into own package: 

https://github.com/felixblaschke/sa3_liquid
https://pub.dev/packages/sa3_liquid

**Comment by fisforfaheem** [comment]
but its not being updated, also the name of the package is so bland, sorry.  Please update it for flutter 3.10.6 its 22 months old

**Comment by fisforfaheem** [comment]
its such an amazing package why did u stopped it

**Comment by felixblaschke** [comment]
This was more kind of an experiment. It has MIT licence so feel free to continue maintaining it.

**Comment by fisforfaheem** [comment]
I wish I could, but I am no expert, but i think you can relaucnh it with
maybe new name,, as i cant find anything like it
