### ISSUE TITLE
Compatibility with Flutter 3.13

### ISSUE THREAD

**Issue by bernat-gomez** [felixblaschke/simple_animations#102]
**Description** 

When compiling with latest Flutter stable version (3.13) any client app that uses the library, an error is raised in the class "**animation_mixin.dart**"

**Trace**
`
animation_mixin.dart:139:56: Error: A value of type 'ValueListenable<bool>' can't be assigned to a variable of type 'ValueNotifier<bool>'.
final ValueNotifier<bool> newNotifier = TickerMode.getNotifier(context);
`

**Info**
[!] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-ES)
    • Flutter version 3.13.0 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (35 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK
    • Platform android-33, build-tools 33.0.2
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Mi A2 (mobile)  • 27706dc • android-arm64  • Android 10 (API 29)
    • macOS (desktop) • macos   • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome  • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

**Comment by felixblaschke** [comment]
Have you tried updating simple_animations to 5.0.2?

Duplicate to https://github.com/felixblaschke/simple_animations/issues/100

**Comment by felixblaschke** [comment]
@vega-labs this looks like a local issue with your flutter. Have you tried deleting the `.pub-cache `?
If this persists, can you create a simple sample repo that shows the error?

**Comment by felixblaschke** [comment]
Thanks for the investigation.

Then it would be cool to have a sample repo where this error occurs, so I can reproduce it locally.

**Comment by felixblaschke** [comment]
Yeah it got renamed to `LoopAnimationBuilder`

**Comment by bernat-gomez** [comment]
Thanks for the response Felix, we will check
