### ISSUE TITLE
How to repeat with a pause

### ISSUE THREAD

**Issue by nebis-software** [felixblaschke/simple_animations#103]
Hi,
    thanks for the very nice package, it's a lifesaver :)

Let me ask a question: how can i repeat with a pause? For example, in the below snippet I animate a button translating it left/right , trying to catch some user attention. It would be nice to animate it for a while, stop, then restart, etc etc.
Any idea? Thanks!!!!

```dart
MirrorAnimationBuilder<double>(
                    tween: Tween(begin: 0, end: -30),
                    curve: Curves.decelerate,
                    duration: const Duration(milliseconds: 500),
                    builder: (context, value, _) {
                      return Transform.translate(
                          offset: Offset(value, 0), // use value
                          child: SvgPicture.asset('assets/images/btn-round.svg'));
                    }),
```

**Comment by felixblaschke** [comment]
Hi. For that you can use the CustomAnimationBuilder, that you can "feed" with a "control value" (e.g. looping, pausing)

Here are some references to read:
- https://github.com/felixblaschke/simple_animations?tab=readme-ov-file#customanimationbuilder
- https://github.com/felixblaschke/simple_animations/blob/main/example/example.md#customanimationbuilder-in-a-stateful-environment

**Comment by nebis-software** [comment]
Thanks for the hint! I finally ended up using scenes:

```dart
    final tween = MovieTween()
      ..scene(
        begin: const Duration(seconds: 0),
        duration: const Duration(seconds: 2),
      )
          .tween('x', ConstantTween<double>(0))
          .thenFor(
            delay: const Duration(milliseconds: 1000),
            duration: const Duration(seconds: 2),
          )
          .tween(
            'x',
            Tween<double>(begin: 0, end: -SfUiTheme(context).cardPadding),
            curve: Curves.decelerate,
          );
```
