### ISSUE TITLE
Is it possible to animate items in Listview.builder only when user is scrolling up but not when they are scrolling down

### ISSUE THREAD

**Issue by MichaelSowah** [felixblaschke/simple_animations#16]
Is it possible to animate items in Listview.builder only when the user is scrolling up but not when they are scrolling down?

**Comment by felixblaschke** [comment]
I guess you are using the ControlledAnimation widget. It get processed (e.g. starting animation and stuff) when it's created. The Listview creates widgets when it comes into the view. So there is no chance of realizing that it's coming from top or bottom.

For this propose you need to track the visibility of your widget yourself from the outside of your Listview. Then you can pass in the proper behavior.

**Comment by MichaelSowah** [comment]
So which animation widget can I use to get this without getting the same effect as the ControlledAnimation widget?

**Comment by felixblaschke** [comment]
ControlledAnimation itself can't detect where it's used. It just handles/renders an animation.

You need fetch die scroll events of your listview. Then you'll need to consider whether it should animate or note. Depending on that you use ControlledAnimation. (Setting the animation duration to 1ms will have an "no-animation" effect)

Here is a good start for this topic: https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac
