### ISSUE TITLE
Animation Rebuilding Multiple Widgets

### ISSUE THREAD

**Issue by KaushickSArgekar** [felixblaschke/simple_animations#20]
When  we set state in one of Controllered  animation widget all
 other Controllerd animation widgets rebuild even when using builder with child

**Comment by felixblaschke** [comment]
Can you please provide a simplified example (as code) of the whole situation you are trying to implement. So I can test it on my own computer. That way it's easier for me to understand what you want to achieve and to help you.

**Comment by KaushickSArgekar** [comment]
import 'package:async_loader/async_loader.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:googly/common/app_background.dart';
import 'package:googly/common/custom_widgets.dart';
import 'package:googly/features/dashboard/features/packsview/features/gameboard/repo/gameBoard.repo.dart';
import 'package:googly/model/googly.model.dart';
import 'package:googly/services/ui.service.dart';
import 'package:simple_animations/simple_animations.dart';

class GameBoardPage extends StatefulWidget {
  final Pack pack;

  GameBoardPage({@required this.pack});

  @override
  _GameBoardPageState createState() => _GameBoardPageState();
}

class _GameBoardPageState extends State<GameBoardPage> {
  final GlobalKey<AsyncLoaderState> _asyncLoaderState =
      new GlobalKey<AsyncLoaderState>();

  @override
  Widget build(BuildContext context) {
    final levelData = widget.pack;

    final _gameBoard = AsyncLoader(
      key: _asyncLoaderState,
      initState: () => GameBoardRepo.iniGameBoard(levelData),
      renderLoad: () => CustomWidgets.showLoadingWidget(),
      renderError: ([err]) => Text('Something went Wrong'),
      renderSuccess: ({data}) => _generateGameBoard(data),
    );

    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Colors.white,
      body: Stack(
        alignment: Alignment.center,
        fit: StackFit.expand,
        children: <Widget>[AppBackground(), _gameBoard],
      ),
    );
  }

  _generateGameBoard(Widget typeWidget) {
    final levelData = widget.pack;

    final tween = MultiTrackTween([
      Track("mimeHeight").add(Duration(milliseconds: 500),
          Tween(begin: 0.0, end: UIService.getHeight(context) / 2.0)),
      Track("mimeWidth").add(Duration(milliseconds: 500),
          Tween(begin: 0.0, end: UIService.getWidth(context))),
      Track("bubble").add(
          Duration(milliseconds: 500), Tween<double>(begin: 0.0, end: 1.0),
          curve: Curves.elasticOut)
    ]);

    final _optionsTextStyle = TextStyle(
      color: Colors.blueGrey[800],
      fontSize: 20,
      fontFamily: 'QSSM',
    );

    final mimeHolder = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      duration: tween.duration,
      tween: tween,
      builder: (context, anim) {
        return SizedBox(
          width: anim["mimeWidth"],
          height: anim["mimeHeight"],
          child: Card(
            color: Colors.transparent,
            margin: EdgeInsets.all(0.0),
            elevation: 10,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(35.0),
              bottomRight: Radius.circular(35.0),
            )),
            child: ClipRRect(
              borderRadius: BorderRadius.only(
                bottomLeft: Radius.circular(35.0),
                bottomRight: Radius.circular(35.0),
              ),
              child: typeWidget,
            ),
          ),
        );
      },
    );

    final _question = Container(
      margin: EdgeInsets.fromLTRB(26, 10, 10, 10),
      child: CustomWidgets.typeWriterWidget(levelData.question),
    );

    final _optionA = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2000),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "A",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionB,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    final _optionB = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2200),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "B",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionC,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    final _optionC = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2400),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "C",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionA,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: <Widget>[mimeHolder, _question, _optionA, _optionB, _optionC],
    );
  }
}

Here if I change the state of a _optionA the _optionB also animates

**Comment by KaushickSArgekar** [comment]
Thanks for replying
here is the issue if i try to change the _optionA state the _optionB state
also changes(Even I am using builder with child
)


import 'package:async_loader/async_loader.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:googly/common/app_background.dart';
import 'package:googly/common/custom_widgets.dart';
import
'package:googly/features/dashboard/features/packsview/features/gameboard/repo/gameBoard.repo.dart';
import 'package:googly/model/googly.model.dart';
import 'package:googly/services/ui.service.dart';
import 'package:simple_animations/simple_animations.dart';

class GameBoardPage extends StatefulWidget {
  final Pack pack;

  GameBoardPage({@required this.pack});

  @override
  _GameBoardPageState createState() => _GameBoardPageState();
}

class _GameBoardPageState extends State<GameBoardPage> {
  final GlobalKey<AsyncLoaderState> _asyncLoaderState =
      new GlobalKey<AsyncLoaderState>();

  @override
  Widget build(BuildContext context) {
    final levelData = widget.pack;

    final _gameBoard = AsyncLoader(
      key: _asyncLoaderState,
      initState: () => GameBoardRepo.iniGameBoard(levelData),
      renderLoad: () => CustomWidgets.showLoadingWidget(),
      renderError: ([err]) => Text('Something went Wrong'),
      renderSuccess: ({data}) => _generateGameBoard(data),
    );

    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Colors.white,
      body: Stack(
        alignment: Alignment.center,
        fit: StackFit.expand,
        children: <Widget>[AppBackground(), _gameBoard],
      ),
    );
  }

  _generateGameBoard(Widget typeWidget) {
    final levelData = widget.pack;

    final tween = MultiTrackTween([
      Track("mimeHeight").add(Duration(milliseconds: 500),
          Tween(begin: 0.0, end: UIService.getHeight(context) / 2.0)),
      Track("mimeWidth").add(Duration(milliseconds: 500),
          Tween(begin: 0.0, end: UIService.getWidth(context))),
      Track("bubble").add(
          Duration(milliseconds: 500), Tween<double>(begin: 0.0, end: 1.0),
          curve: Curves.elasticOut)
    ]);

    final _optionsTextStyle = TextStyle(
      color: Colors.blueGrey[800],
      fontSize: 20,
      fontFamily: 'QSSM',
    );

    final mimeHolder = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      duration: tween.duration,
      tween: tween,
      builder: (context, anim) {
        return SizedBox(
          width: anim["mimeWidth"],
          height: anim["mimeHeight"],
          child: Card(
            color: Colors.transparent,
            margin: EdgeInsets.all(0.0),
            elevation: 10,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(35.0),
              bottomRight: Radius.circular(35.0),
            )),
            child: ClipRRect(
              borderRadius: BorderRadius.only(
                bottomLeft: Radius.circular(35.0),
                bottomRight: Radius.circular(35.0),
              ),
              child: typeWidget,
            ),
          ),
        );
      },
    );

    final _question = Container(
      margin: EdgeInsets.fromLTRB(26, 10, 10, 10),
      child: CustomWidgets.typeWriterWidget(levelData.question),
    );

    final _optionA = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2000),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "A",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionB,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    final _optionB = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2200),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "B",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionC,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    final _optionC = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2400),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "C",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionA,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: <Widget>[mimeHolder, _question, _optionA, _optionB,
_optionC],
    );
  }
}

**Comment by KaushickSArgekar** [comment]
Here is the below scenario 

If the change the state of _optionA the _optionB and _optionC also animates. 

  Playback _optionAPlayBack = Playback.PLAY_FORWARD;
  Playback _optionBPlayBack = Playback.PLAY_FORWARD;
  Playback _optionCPlayBack = Playback.PLAY_FORWARD;


 final tween = MultiTrackTween([
      Track("mimeHeight").add(Duration(milliseconds: 500),
          Tween(begin: 0.0, end: UIService.getHeight(context) / 2.0)),
      Track("mimeWidth").add(Duration(milliseconds: 500),
          Tween(begin: 0.0, end: UIService.getWidth(context))),
      Track("bubble").add(
          Duration(milliseconds: 500), Tween<double>(begin: 0.0, end: 1.0),
          curve: Curves.elasticOut)
    ]);


final _optionA = ControlledAnimation(
      playback: playback,
      duration: tween.duration,
      tween: tween,
      delay: Duration(milliseconds: 2000),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: InkWell(
            onTap: () {
              setState(() {
                playback = Playback.START_OVER_FORWARD;
              });
            },
            child: SizedBox(
              width: UIService.getWidth(context),
              height: 80,
              child: Card(
                elevation: 4,
                color: Colors.white,
                margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
                shape: UIService.getRoundedCornerCardShape(30.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    SizedBox(
                      width: 20,
                    ),
                    CircleAvatar(
                      backgroundColor: Colors.grey[200],
                      radius: 20,
                      child: Text(
                        "A",
                        style: TextStyle(
                            fontFamily: 'QSB',
                            fontSize: 25,
                            color: Colors.blueGrey[700]),
                      ),
                    ),
                    SizedBox(
                      width: 20,
                    ),
                    Flexible(
                      child: AutoSizeText(
                        levelData.optionB,
                        style: _optionsTextStyle,
                        maxLines: 1,
                      ),
                    ),
                    SizedBox(
                      width: 20,
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );

    final _optionB = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2200),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "B",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionC,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

    final _optionC = ControlledAnimation(
      playback: Playback.PLAY_FORWARD,
      tween: tween,
      duration: tween.duration,
      delay: Duration(milliseconds: 2400),
      builder: (context, anim) {
        return Transform.scale(
          scale: anim["bubble"],
          child: SizedBox(
            width: UIService.getWidth(context),
            height: 80,
            child: Card(
              elevation: 4,
              color: Colors.white,
              margin: EdgeInsets.fromLTRB(20, 10, 20, 10),
              shape: UIService.getRoundedCornerCardShape(30.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  SizedBox(
                    width: 20,
                  ),
                  CircleAvatar(
                    backgroundColor: Colors.grey[200],
                    radius: 20,
                    child: Text(
                      "C",
                      style: TextStyle(
                          fontFamily: 'QSB',
                          fontSize: 25,
                          color: Colors.blueGrey[700]),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Flexible(
                    child: AutoSizeText(
                      levelData.optionA,
                      style: _optionsTextStyle,
                      maxLines: 1,
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );

**Comment by felixblaschke** [comment]
Thanks for providing some code. Your code snippet isn't a complete app/widget so I need to assume some facts. I created an example widget that tries to mimic your logic. It's working as intended. (See code below)

Maybe there are some destruction actions happening that causing your widget tree to reconstruct? Or maybe there is some strange reusage of widgets happening in your app. Providing some unique keys for your widgets may help. (See #17 )

If this doesn't help you please provide a more complete example, starting with a whole widget that contains all logic and animations.

```dart
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: SafeArea(child: MyHomePage())),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Playback playback = Playback.PLAY_FORWARD;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            ControlledAnimation(
              playback: playback,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.red);
              },
            ),
            ControlledAnimation(
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.blue);
              },
            ),
            ControlledAnimation(
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.yellow);
              },
            )
          ],
        ),
        Row(children: <Widget>[
          MaterialButton(
            child: Text("Replay first one"),
            onPressed: () {
              setState(() {
                playback = Playback.START_OVER_FORWARD;
              });
            },
          )
        ],)
      ],
    );
  }
}

```

**Comment by KaushickSArgekar** [comment]
Hey Thanks for replay 

Here I added one more playback for widget blue and changed the state on click for widget 2 
error:-The red also animated on replaying the blue widget




import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: SafeArea(child: MyHomePage())),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Playback playback = Playback.PLAY_FORWARD;
  Playback playback2 = Playback.PLAY_FORWARD;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            ControlledAnimation(
              playback: playback,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.red);
              },
            ),
            ControlledAnimation(
              playback: playback2,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.blue);
              },
            ),
            ControlledAnimation(
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.yellow);
              },
            )
          ],
        ),
        Row(
          children: <Widget>[
            MaterialButton(
              child: Text("Replay first one"),
              onPressed: () {
                setState(() {
                  playback = Playback.START_OVER_FORWARD;
                });
              },
            ),
            MaterialButton(
              child: Text("Replay second one"),
              onPressed: () {
                setState(() {
                  playback2 = Playback.START_OVER_FORWARD;
                });
              },
            ),
          ],
        )
      ],
    );
  }
}

**Comment by KaushickSArgekar** [comment]
and  I Tried with the below code also using Labeled Key Same issue


import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: SafeArea(child: MyHomePage())),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Playback playback = Playback.PLAY_FORWARD;
  Playback playback2 = Playback.PLAY_FORWARD;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            ControlledAnimation(
              key: LabeledGlobalKey("sdsdsds"),
              playback: playback,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 1.0),
              child: FlutterLogo(),
              builderWithChild: (context,child, anim) {
                return Transform.scale(scale: anim,child: child,);

              },
            ),
            ControlledAnimation(
              key: LabeledGlobalKey("sdsdssdsdsdsdsdsdds"),
              playback: playback2,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 1.0),
              child: FlutterLogo(),
              builderWithChild: (context,child, anim) {
                return Transform.scale(scale: anim,child: child,);

              },
            ),
            ControlledAnimation(

              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.yellow);
              },
            )
          ],
        ),
        Row(
          children: <Widget>[
            MaterialButton(
              child: Text("Replay first one"),
              onPressed: () {
                setState(() {
                  playback = Playback.START_OVER_FORWARD;
                });
              },
            ),
            MaterialButton(
              child: Text("Replay second one"),
              onPressed: () {
                setState(() {
                  playback2 = Playback.START_OVER_FORWARD;
                });
              },
            ),
          ],
        )
      ],
    );
  }
}

**Comment by felixblaschke** [comment]
Ok I figured out what's not clear. Everytime you call `setState` the widget tree is rebuilded. The `ControlledAnimation` looks for the playback property. If it's set to `START_OVER_FORWARD` it will replay, no matter what. In opposite `PLAY_FORWARD` will keep it's current animation position.

The solution is to manually keep track of the `playback` variables (playback1, playback2 and so on) and assure that only **one** is set to `START_OVER_FORWARD` at the same time.

Example:
```dart
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: SafeArea(child: MyHomePage())),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  Playback playback = Playback.PLAY_FORWARD;
  Playback playback2 = Playback.PLAY_FORWARD;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ControlledAnimation(
              playback: playback,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.red);
              },
            ),
            ControlledAnimation(
              playback: playback2,
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.blue);
              },
            ),
            ControlledAnimation(
              duration: Duration(seconds: 1),
              tween: Tween(begin: 0.0, end: 100.0),
              builder: (context, anim) {
                return Container(
                    width: 100, height: 100 + anim, color: Colors.yellow);
              },
            )
          ],
        ),
        Row(
          children: [
            MaterialButton(
              child: Text("Replay first one"),
              onPressed: () {
                setState(() {
                  playback = Playback.START_OVER_FORWARD;
                  playback2 = Playback.PLAY_FORWARD;
                });
              },
            ),
            MaterialButton(
              child: Text("Replay second one"),
              onPressed: () {
                setState(() {
                  playback = Playback.PLAY_FORWARD;
                  playback2 = Playback.START_OVER_FORWARD;
                });
              },
            ),
          ],
        )
      ],
    );
  }
}

```

Does this solves your issue?

**Comment by KaushickSArgekar** [comment]
Thanks, @felixblaschke  My issues are solved,
Thanks for all the information  and your time. The https://github.com/felixblaschke/simple_animations/issues/20#issuecomment-588156938

Solved my issue.

**Comment by KaushickSArgekar** [comment]
Thanks Felixblaschke/Simple_animations

This solved the problem
