### ISSUE TITLE
Graphical issue

### ISSUE THREAD

**Issue by Azzeccagarbugli** [felixblaschke/simple_animations#22]
Hi @felixblaschke,

First of all thanks for this amazing package that you created, is really awesome!

I discovered it by reading [this](https://medium.com/@felixblaschke/fancy-background-animations-in-flutter-4163d50f5c37) article that you posted on Medium and I was just stunned by the simplicity provided by this software so I managed to follow it _step-by-step_ and reproduce it.

There is just one problem, I tried to achieve a different effect rather than the one proposed, I mean I would like to see all the sine wave and **not just half**. 

The one that is described is more or less something like this: 

![image](https://user-images.githubusercontent.com/16477661/76131609-698f5b00-600f-11ea-9ba8-47e15af980d3.png)

The one that I'm trying to achieve is, hypothetically, like this:

![image](https://user-images.githubusercontent.com/16477661/76131642-95aadc00-600f-11ea-9bc2-8310536555d1.png)
 
I think that the problem is inside the following snippet to code, but I really don't know hot to _fix_ this.

``` dart
class CurvePainter extends CustomPainter {
  final double value;

  CurvePainter(this.value);

  @override
  void paint(Canvas canvas, Size size) {
    final white = Paint()..color = Colors.white.withAlpha(60);
    final path = Path();

    final y1 = sin(value);
    final y2 = sin(value + pi / 2);
    final y3 = sin(value + pi);

    final startPointY = size.height * (0.5 + 0.4 * y1);
    final controlPointY = size.height * (0.5 + 0.4 * y2);
    final endPointY = size.height * (0.5 + 0.4 * y3);

    path.moveTo(size.width * 0, startPointY);
    path.quadraticBezierTo(
        size.width * 0.5, controlPointY, size.width, endPointY);
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.close();
    canvas.drawPath(path, white);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

I hope that I was clear enough, thanks in advance!

**Comment by felixblaschke** [comment]
Hi! In my article I defined the wave as **just one curve**. I applied clever values derived from a sine function that made it look like a sine wave.

If you want to display a complete sine wave in that style, you need a different approach. The easiest way is to sample the sine function itself:

```dart
class CurvePainter extends CustomPainter {
  final double value;

  CurvePainter(this.value);

  @override
  void paint(Canvas canvas, Size size) {
    final white = Paint()..color = Colors.red.withAlpha(60);
    final path = Path();

    var first = true;

    var stepSize = pi * 0.1;

    for (var x = 0 * pi - stepSize; x <= 2 * pi + stepSize; x += stepSize) {
      if (first) {
        path.moveTo(
            x / (2 * pi) * size.width, sin(x + value) * 0.4 * size.height);
        first = false;
      } else {
        path.quadraticBezierTo(
            (x - 0.5 * stepSize) / (2 * pi) * size.width,
            sin(x - (0.5 * stepSize) + value) * 0.4 * size.height,
            x / (2 * pi) * size.width,
            sin(x + value) * 0.4 * size.height);
      }
    }

    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.close();
    canvas.drawPath(path, white);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```
The variable stepSize defines the sample size. The more you lower it, the better it looks, but also increased amount of computation.

**Comment by Azzeccagarbugli** [comment]
Thanks a lot @felixblaschke for the really quick answer.

Now what I get when I run your snippet of code is this animation:

![image](https://user-images.githubusercontent.com/16477661/76142919-73967580-6072-11ea-88ca-29a6ebac1345.png)

What I would like to have, instead, is something that **doesn't end flat in the bottom**.

Something like this:

![Screenshot_20200307_125659 (1)](https://user-images.githubusercontent.com/16477661/76143052-ef44f200-6073-11ea-80f2-11c4d8165f31.png)

Obviously I would like to control the thickness of the curve so that the effect would be more interesting.  

Forgive me if I wasn't clear enough before, I hope that now you understood me.

Thanks again for you availability!

**Comment by felixblaschke** [comment]
Ah! You just want to draw a sine line. That's even simplier:

```dart
class CurvePainter extends CustomPainter {
  final double value;

  CurvePainter(this.value);

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.red.withAlpha(60)
      ..strokeWidth = 5;

    var stepSize = pi * 0.05;

    final heightScale = 0.4;
    for (var x = 0 * pi; x <= 2 * pi; x += stepSize) {
      final p1 = Offset((x - stepSize) / (2 * pi) * size.width, sin(x - stepSize + value) * heightScale * size.height);
      final p2 = Offset(x / (2 * pi) * size.width, sin(x + value) * heightScale * size.height);
      canvas.drawLine(p1, p2, paint);
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

![image](https://user-images.githubusercontent.com/26407468/76143340-e99cdb80-6076-11ea-9ccb-6edf4f55ea1f.png)

**Comment by Azzeccagarbugli** [comment]
That's perfect!

How can I simply increase the thickness of the wave? So in this way will be more visible.
