### ISSUE TITLE
Animation starting from different offset even the starting position is same 

### ISSUE THREAD

**Issue by KaushickSArgekar** [felixblaschke/simple_animations#26]
`import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';

void main()=>runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Example(),
    );
  }
}

class Example extends StatefulWidget {
  @override
  _ExampleState createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  @override
  Widget build(BuildContext context) {

    final _tween=MultiTrackTween([
      Track('slide').add(Duration(milliseconds: 5000),
          Tween<Offset>(begin: Offset(70, 70), end: Offset.zero),)
    ]);

    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            ControlledAnimation(
              tween: _tween,
              duration: _tween.duration,
              playback: Playback.PLAY_FORWARD,
              builder: (c,a){
                return Transform.translate(offset: a['slide'],child: FlutterLogo(),);
              },
            ),
            ControlledAnimation(
              tween: _tween,
              duration: _tween.duration,
              playback: Playback.PLAY_FORWARD,
              builder: (c,a){
                return Transform.translate(offset: a['slide'],child: FlutterLogo(),);
              },
            )
          ],
        ),
      ),
    );

  }
}

`

**Comment by felixblaschke** [comment]
Hi! What's the problem with this? I tried it and saw some flutter logos animating. :-)

**Comment by KaushickSArgekar** [comment]
The problem is that when I use the Two widgets in Row and gave a distance between them and animate them using the same offset the widgets will not start from the same positions.
there is a gap between them.

**Comment by felixblaschke** [comment]
A translation (in terms of computer graphics) is to move an object from it's original position for a given offset into a certain direction.

At the start of the animation you tell Flutter to displace both logos 70 units to bottom right (`Offset(70, 70)`) from it's original position. While the animation progress the translation is reduced to zero. That's why at the end it appears centered.

Made a video of it: https://youtu.be/i4p9DeIhSuQ

I dont see any additional gap while animating. Both logos have the same distance between them. They are just flying in from bottom right to the center.

**Comment by KaushickSArgekar** [comment]
Thanks for replying.

I shared two videos that execute my issue.

1) When I use only one widget with the same Tween offset it works fine,
example:- 
https://drive.google.com/file/d/10ZoRKgE14zgO7sHfHhN76iHmQfTttbi4/view?usp=sharing.


2) But if I use two widgets them the animation starting points have a distance in them.
it doesn't start with the same offset.
example:- 
https://drive.google.com/file/d/1CsVlhROeZLqp8kdHJjSKbKwNTrLBCzex/view?usp=sharing


Thanks in advance.

**Comment by felixblaschke** [comment]
Okay, now I got an idea. Both buttons should start from the same spot. That's not an issue with this package. You just need to change the way you are layouting. The code from above works as intended.

You might need an additional translation to push both button together:

```dart
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Example(),
    );
  }
}

class Example extends StatefulWidget {
  @override
  _ExampleState createState() => _ExampleState();
}

class _ExampleState extends State {
  @override
  Widget build(BuildContext context) {
    var screenSize = MediaQuery.of(context).size;

    final _tween = MultiTrackTween([
      Track('translate').add(
        Duration(milliseconds: 2000),
        Tween<Offset>(
            begin: Offset(
                screenSize.width / 2.0 + 10, screenSize.height / 2.0 + 10),
            end: Offset.zero),
      ),
      Track('scale').add(
        Duration(milliseconds: 2000),
        Tween(begin: 0.0, end: 1.0),
      ),
      Track('merge').add(
        Duration(milliseconds: 2000),
        Tween(begin: 50.0, end: 0.0),
        curve: Curves.easeOut
      ),
    ]);

    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
        child: ControlledAnimation(
          tween: _tween,
          duration: _tween.duration,
          curve: Curves.easeOut,
          playback: Playback.MIRROR,
          builder: (c, a) {
            return Transform.translate(
              offset: a['translate'],
              child: Transform.scale(
                scale: a['scale'],
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Transform.translate(
                      offset: Offset(a['merge'], 0),
                      child: FlutterLogo(
                        size: 100,
                        colors: Colors.green,
                      ),
                    ),
                    Transform.translate(
                      offset: Offset(-a['merge'], 0),
                      child: FlutterLogo(
                        size: 100,
                        colors: Colors.red,
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by KaushickSArgekar** [comment]
Thanks a lot for explaining.

**Comment by KaushickSArgekar** [comment]
Can you send me the code for this type of animation?

https://drive.google.com/file/d/1CsVlhROeZLqp8kdHJjSKbKwNTrLBCzex/view?usp=sharing

I am unable to solve it.

Thank you.

**Comment by felixblaschke** [comment]
I mentioned a similar approach at my last comment: https://github.com/felixblaschke/simple_animations/issues/26#issuecomment-612787338

Sorry but I have not the time to create project-specific custom animations. If don't feel able to realize that, you can ask someone at Stackoverflow to help you with this.

**Comment by KaushickSArgekar** [comment]
Ok no problem Thanks
