### ISSUE TITLE
Animation curve property doesn't update from state

### ISSUE THREAD

**Issue by benPesso** [felixblaschke/simple_animations#27]
Assuming the following widget:
```dart
ControlledAnimation(
      child: child,
      curve: animateOut ? Curves.easeIn : Curves.elasticOut,
      duration: duration,
      playback: animateOut ? Playback.PLAY_REVERSE : Playback.PLAY_FORWARD,
      tween: tween,
      ...
)
```

When calling `setState(() => animateOut = !animateOut);` one expects the `curve` to be updated as well, but that is not the case.

By the way, if modified in the `state`, the `duration` property *does* get the new value.

**Comment by felixblaschke** [comment]
Thank you for reporting that bug. 

I could identify the problem. Version `1.3.12` will fix that issue.

Can you try that version and verify that it's working for you? 😃

**Comment by benPesso** [comment]
Works like a charm. Thanks!

21 minutes to publish a bugfix... Must be some kind of a record. 😄
