### ISSUE TITLE
Medium articles refer MultiTrackTween and ControlledAnimation (Confusing)

### ISSUE THREAD

**Issue by vinnytwice** [felixblaschke/simple_animations#28]
Hi,I'm just starting to explore animations in Flutter and I just found your plugin and it seem fantastic. I see that in your articles on Medium https://medium.com/@felixblaschke/fancy-background-animations-in-flutter-4163d50f5c37 you use a MultiTrackTween but I don't see it in the docs nor the plugin. 
in the code 
```
class AnimatedBackground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final tween = MultiTrackTween([
      Track("color1").add(Duration(seconds: 3),
          ColorTween(begin: Color(0xffD38312), end: Colors.lightBlue.shade900)),
      Track("color2").add(Duration(seconds: 3),
          ColorTween(begin: Color(0xffA83279), end: Colors.blue.shade600))
    ]);

    return ControlledAnimation(
      playback: Playback.MIRROR,
      tween: tween,
      duration: tween.duration,
      builder: (context, animation) {
        return Container(
          decoration: BoxDecoration(
              gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [animation["color1"], animation["color2"]])),
        );
      },
    );
  }
}
```
both the MultiTrackTween and ControlledAnimation are not found from the plugin. Aren't they from it?
Thank you very much.
Cheers

**Comment by felixblaschke** [comment]
Hello, welcome to the Flutter ecosystem. It's cool here :-)

You are right, these classes are from Simple Animations. But I released a new version 2.x last week where everything is a bit different. Thanks for reminding me that I need to add a note to my articles.

You can find the v2 updated examples at: https://github.com/felixblaschke/simple_animations/blob/master/example/lib/examples/fancy_background.dart

To have an overview what changed, you can look at https://pub.dev/packages/sa_v1_migration.

To get an overview have a look at the readme documentation at https://pub.dev/packages/simple_animations.

Happy Animating!

**Comment by MostHated** [comment]
I was having this same issue. I opened up a prior project and ran into some issues relating to that. It took me a few to figure out what was up. Is it possible to mark those items using the tween tracks as deprecated somehow? I know I see it done often, I just have never done it myself so I am not sure if it is complicated to implement. I just know it's helpful when trying to figure out what is different.

Thanks,
-MH

**Comment by MostHated** [comment]
Well shoot, without there being a ControlledAnimation in the new Library (at least not that I saw, unless it was moved into one of the other ones?), how might I go about accomplishing this below?

 I used things like this all the time to only have things play once, and other similar conditions. Am I just going to have to stick to the old library, or is something new going to take it's place?

```dart
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';
import 'package:sa_v1_migration/sa_v1_migration.dart';
import 'package:supercharged/supercharged.dart';

import 'anim_properties.dart';

AnimationStatusListener animStatus;
bool _setupComplete = false;
bool get setupComplete => _setupComplete;
set setupComplete(bool completed) => _setupComplete = completed;

void _listenToAnimationFinished(status) {
  if (status == AnimationStatus.completed) {
    setupComplete = false;
  }
}

class SlideFadeIn extends StatelessWidget {
  SlideFadeIn({Key key, this.delay, this.child}) : super(key: key);

  final double delay;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final tween = MultiTrackTween([
      Track("opacity")
          .add(Duration(milliseconds: 500), Tween(begin: 0.0, end: 1.0)),
      Track("translateX").add(
          Duration(milliseconds: 500), Tween(begin: 130.0, end: 0.0),
          curve: Curves.easeOut)
    ]);

    return ControlledAnimation(
      delay: Duration(milliseconds: (300 * delay).round()),
      duration: tween.duration,
      tween: tween,
      playback: _setupComplete ? Playback.PAUSE : Playback.PLAY_FORWARD,
      child: child,
      builderWithChild: (context, child, animation) => Opacity(
        opacity: animation["opacity"],
        child: Transform.translate(offset: Offset(animation["translateX"], 0), child: child),
      ),
      animationControllerStatusListener: _listenToAnimationFinished,
    );
  }
}

```

**Comment by vinnytwice** [comment]
@felixblaschke I see. I actually thought of it, I didn't notice the migration part. Thank you, time to dive into the docs then. Cheers.

**Comment by felixblaschke** [comment]
> Well shoot, without there being a ControlledAnimation in the new Library (at least not that I saw, unless it was moved into one of the other ones?), how might I go about accomplishing this below?
> 
> I used things like this all the time to only have things play once, and other similar conditions. Am I just going to have to stick to the old library, or is something new going to take it's place?

There is a widget `CustomAnimation` that's pretty similar to `ConstrolledAnimation`. For `MultiTrackTween` there is a type-safe option `MultiTween`.

For more information look at: https://pub.dev/packages/sa_v1_migration

I'll thinking about integrating the migration package into simple_animation and mark the previous API as deprecated.

**Comment by felixblaschke** [comment]
I made a release `2.1.0` of simple_animations that contains all the v1 classes. They have a deprecation annotation with the link to the migration guide.

Upgrading project can now upgrade simpler and softer. Thank you for noticing that.

**Comment by felixblaschke** [comment]
I also added a note to prevous articles on medium.

For example: https://medium.com/@felixblaschke/fancy-background-animations-in-flutter-4163d50f5c37
