### ISSUE TITLE
Add a delay to MultiTween

### ISSUE THREAD

**Issue by scullabyte** [felixblaschke/simple_animations#29]
First off, great libraries here! Let me know if I'm missing something, but it looks like the MultiTween can add individual durations, but there is only one delay per widget, right? 

The effect I'm looking for is similar to `flutter_sequence_animation`, where I can have a widget animate the opacity, then when that is done animate that widget's color, then the border, etc... All on the same widget, with one animation starting after the other is completed (or some time after).

If this is something I can currently do with `simple_animations` let me know. Otherwise, let me know if you'd be open to me submitting a pull request to `MultiTween` and `MultiTweenValues` to add an optional parameter `delay`

**Comment by scullabyte** [comment]
Nevermind, I found the solution after looking more carefully through your example code. Feel free to delete this. If anyone else has this problem, I discovered that you can just add 2 tweens of the same enum, with the first one being the same value twice. So, like:

```dart
    final _tween = MultiTween<AniProps>()
      ..add(AniProps.depth, 0.0.tweenTo(widget.elevation), 300.milliseconds,
          Curves.bounceInOut)
      ..add(AniProps.color, _outerColor.tweenTo(_outerColor), 500.milliseconds)  // <-- Note this
      ..add(AniProps.color, _outerColor.tweenTo(_appColor), 200.milliseconds)
      ..add(AniProps.text_opacity, 0.0.tweenTo(0.0), 400.milliseconds)  // <-- and this
      ..add(AniProps.text_opacity, 0.0.tweenTo(1.0), 400.milliseconds)
      ..add(AniProps.opacity, 0.0.tweenTo(1.0), 200.milliseconds);

```
To get the `text_opacity` enum to start after 500 ms, I just 'tweened' the same from 0.0 to 0.0, then added my real animation tween after. A delay option would be nice, but this is totally sufficient as-is. Thanks again!

**Comment by felixblaschke** [comment]
Thank you for your feedback. Yes you can add the enum multiples times to chain tweens. Good job finding the solution. 😄

**Comment by netgfx** [comment]
Not sure if this will affect performance though, traditionally a simple delay property would be used as well as conceptually it is more robust and easy to use/understand.
