### ISSUE TITLE
Another exception was thrown: parametric value -0.00XXXXX is outside of [0,1] range when using opacity and translate Tween

### ISSUE THREAD

**Issue by jeydi243** [felixblaschke/simple_animations#30]
Hello! I facing this issue every time before de object want to be animate. Please check my github repo. To run:

1. `flutter run`
2. in Home screen click on _Car_ Card and see what happen.
Thank you.

**Comment by felixblaschke** [comment]
Dont use `Curves.easeInOutBack` as a curve for your `PlayAnimation` in combination with `MultiTween`.

`Curves.easeInOutBack` produces negatives values and values above 1.0. MultiTween doesn't know what to do with "negative time". If you apply that to your opacity property it will result in errors too.

`Curves.easeInOutBack` is meant to apply on positional (i.e. offset-based) properties like transform. You can apply it only that one by using the `curve` property inside the `add` method.

Example:
```dart
  final _tween = MultiTween<AniProps>()
    ..add(
      // top left => top right
        AniProps.offset,
        Tween(begin: Offset(-100, -100), end: Offset(100, -100)),
        1000.milliseconds, Curves.easeInOutBack)
```

**Comment by jeydi243** [comment]
thank you sir !
