### ISSUE TITLE
Proper way to animate opacity?

### ISSUE THREAD

**Issue by MostHated** [felixblaschke/simple_animations#31]
Hey there,
    I had been going through and trying to optimize my widgets as much as possible and came across [this article.](https://blog.codemagic.io/how-to-improve-the-performance-of-your-flutter-app./). It looks like simply animating the opacity by value change can eat a lot of performance by causing rebuild per frame. I didn't see opacity being an available item within the default animatable properties for multiwteen, so that made me wonder if there was any special consideration given to opacity when animating that specific property with this package?

If there isn't, do you have any sort of recommendation as to how I might go about incorporating AnimatedOpacity() into a multitween workflow, or might I just need to try and keep that specific property separate?

Thanks!
-MH

**Comment by felixblaschke** [comment]
There are no considerations made 😄 .
MultiTween itself just helps to compute the animation values that will applied somehow to your widget tree. It doesn't differ between opacity (double), offset or something more complex. It just needs to be an `Animatable`.

MultiTween needs something to apply the values on each animation frame. In the `simple_animations` world for example the `PlayAnimation` widget can do this job. It rebuilds everything described in the `builder` function as long as the animation goes.

Here comes performance consideration into mind. The first option is to use the `child` property where you pass in an animation-agnostic part of the widget tree. Inside the `builder` you can just pass thru the child. The child widget isn't rebuilded on each animation frame. ([Example](https://pub.dev/packages/sa_stateless_animation#playanimation-widget-with-a-child))

The second option is to use multiple nested `PlayAnimation` widgets if the animation can be separated. (Meaning that two properties are not animated at the same time / get animated for a different reason or point in time)

Keep in mind that all performance impacts depend on the kind of layout you have. Naturally transformation and opacity are very cheap operation that can be fully computed on GPU level. If you animate opacity in combination with colors of a complex layout it gets expensive cause of the redraw.
