### ISSUE TITLE
Animation when switch grid view to list view.

### ISSUE THREAD

**Issue by IliaMiasoedov** [felixblaschke/simple_animations#32]
Hi! I want to have the animation like this when switch between grid view and list view. Is it possible to do it?
![HtR9K](https://user-images.githubusercontent.com/63303191/83514054-90a8dc00-a4db-11ea-9771-de0ac4466fd5.gif)

Thanks!

**Comment by felixblaschke** [comment]
I'll close this issue since it has no relation to `simple_animations`.
Please notice that this is not a help forum. 

Use the following sites:
- https://flutter.dev/docs/development/ui/animations/hero-animations
- https://www.reddit.com/r/flutterhelp/
