### ISSUE TITLE
ControlledAnimation is deprecated!

### ISSUE THREAD

**Issue by deliciafernandes** [felixblaschke/simple_animations#33]
While using the package simple_animations v2.2.1, ControlledAnimation is deprecated.

**Comment by felixblaschke** [comment]
Yes it's deprecated. What is the goal of your issue?

**Comment by deliciafernandes** [comment]
> Yes it's deprecated. What is the goal of your issue?

What can we use instead?

**Comment by felixblaschke** [comment]
https://pub.dev/packages/sa_v1_migration
