### ISSUE TITLE
Not able to animate opacity changes with PlayAnimation

### ISSUE THREAD

**Issue by mivoligo** [felixblaschke/simple_animations#34]
Please notice that I'm learning Flutter so maybe I'm doing something wrong :)

Anyway I'm trying to use `PlayAnimation()` to animate opacity change. 
In `pubspec.yaml` I use  `simple_animations: ^2.2.1`. 
I created a file `fade_in.dart` which looks like this:
```
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';

class FadeIn extends StatelessWidget {
  final Widget child;

  FadeIn({
    this.child,
  });

  @override
  Widget build(BuildContext context) {
    return PlayAnimation<double>(
      tween: Tween(begin: 0.0, end: 1.0),
      duration: Duration(seconds: 2),
      builder: (context, child, value) {
        return Opacity(
          opacity: value,
          child: child,
        );
      },
    );
  }
}

```
And then in my Home page I try to change opacity of the `Container` like this:

```
            FadeIn(
              child: Container(
                width: 200,
                height: 300,
                color: Colors.amber,
              ),
            ),
```
Unfortunately the Container doesn't show at all.

**Comment by felixblaschke** [comment]
Pass thru your child in PlayAnimation with the child property. (Where you put your tween, duration and builder)

Please note that this is not a support forum. Use https://www.reddit.com/r/flutterhelp/ for support.

**Comment by felixblaschke** [comment]
https://pub.dev/packages/sa_stateless_animation#playanimation-widget-with-a-child

**Comment by mivoligo** [comment]
Thanks for quick response. I know it's not a support forum but I was thinking it could be a real bug as before I've tried similar code with animating width and height of a Container and it worked fine without child property.
