### ISSUE TITLE
Only occupy when fade-in/animating

### ISSUE THREAD

**Issue by jonatadashi** [felixblaschke/simple_animations#35]
How do I making it that it does not occupy space when not faded in. As of now it fades in after said amount of time, but the widget is technically already there, only not animated yet, hence occupying space already.

**Comment by felixblaschke** [comment]
Sorry, please notice this is unrelated to simple_animations since it covers basic layout questions on Flutter.

Please refer to https://www.reddit.com/r/flutterhelp/
