### ISSUE TITLE
Add Repeated Animation feature

### ISSUE THREAD

**Issue by nateshmbhat** [felixblaschke/simple_animations#37]
Sometimes we wish to show an animation only a few number of times , 

so either a `RepeatedPlayAnimation` or a "numberOfTimes" property to `LoopAnimation` would be great !

**Comment by felixblaschke** [comment]
I think limiting the iterations options on `MirrorAnimation` or `PlayAnimation`  will solve this. Good idea. It's quite hard to implement... but i'll keep that issue for further enhancement. 😄

**Comment by felixblaschke** [comment]
I'll close this issue because this feature can be self-implemented by tracking the iterations and stop at a certain point.
