### ISSUE TITLE
Missing ability to tween more than two values per tween

### ISSUE THREAD

**Issue by benPesso** [felixblaschke/simple_animations#38]
There are several cases where this would be convenient. For example, to fade in, then out, while the widget is also animated from left to right, like this:
```dart
MultiTween()
  ..add('position', 0.0.tweenTo(100.0))
  ..add('opacity', 0.0.tweenTo(1.0).tweenTo(0.0))
```

**Comment by felixblaschke** [comment]
Hi! That's a good idea. Do you mind post it here: https://github.com/felixblaschke/supercharged/issues ? Because the `tweenTo` is an extension method coming from supercharged.

**Comment by benPesso** [comment]
Done. Any ideas on how to do that without the supercharged package?

**Comment by felixblaschke** [comment]
Sorry for the later answer.

MultiTween can stack animated properties with multiple `add` calls:

```dart
  final _tween = MultiTween<AniProps>()
    ..add(AniProps.opacity, 0.0.tweenTo(1.0), 1.seconds)
    ..add(AniProps.opacity, 1.0.tweenTo(0.0), 1.seconds)
    ..add(AniProps.position, 0.0.tweenTo(100.0), 2.sesconds)
```

Just use the **duration** to apply weights and created a time releation between **position** and **opacity**. It will start to fade out when position reaches `50.0`. The final duration of the animation is always defined with the `AnimationController` or `PlayAnimation`.
