### ISSUE TITLE
value.get() on enum value not set in the MultiTween()

### ISSUE THREAD

**Issue by nicoroy2561** [felixblaschke/simple_animations#39]
While transitioning to the new MultiTween from the old MultiTrackTween, I encountered a small issue.

My usage might be a little bit weird, but I use a CustomAnimation that gets a different MultiTween according to which animation is to be applied to a particular item. I have a List of MultiTweens from which one gets picked.

I defined an enum with all the values I plan to animate on the item, but I do not animate all of them at once, just a subset of them. Problem is, if I try to use the value.get(myEnum.Valx) the animation library throws an error ("Property 'Valx' does not exist").
So the solutions I found so far are to either ..add each and all those enums to every MultiTween(), or use a trycatch on each of the values when reading them (the latter is what I chose to go with for now). 
Neither of them are elegant, and I am wondering if there's a way to find out wether a particular enum value is present within the builder function of a CustomAnimation widget, or to have the .get() return 'null' rather than an error.

Edit: I checked the source code for the MultiTween and found out the assertion is where I get stuck at. Since the _track is an internal parameter I cannot check wether the value is present or not. I think it'd be better for the function .get() to return null in this case rather than throwing an assertion error, as it should tell the property isn't present (I don't think it's possible to have a Tween return null in any other case).

**Comment by felixblaschke** [comment]
Hi, thank you for explaining your issue.

The old MultiTween had a strong weakness because of dynamic types. The new implementation solves this and reveals unsafe implementations. I imagine that you actually have two different animations and use the tween parameter to to separate between them. There also must be different builders for them to use? Or do you IF/ELSE it?

**Can you please provide an example on how to use it?** Then I'll get a better understanding of what you trying to do. Please understand that I don't want to blindly introduce a nullability feature when the whole dart language is moving away from it with it's next release.

**Comment by nicoroy2561** [comment]
Hi, thank you for your time as always.
I'll make up an example showing my situation to help you understand:

```
enum AniProp { prop1, prop2, prop3, .. }
List<MultiTween<AniProp>> animations = [
      MultiTween()
       ..add(AniProp.prop1, Tween(begin: 0.0, end: 1.0), ..)
       ..add(AniProp.prop2, Tween(begin: 0.0, end: 1.0), ..),
      MultiTween()
       ..add(AniProp.prop1, Tween(begin: 0.0, end: 1.0), ..)
       ..add(AniProp.prop3, Tween(begin: 0.0, end: 1.0), ..),
...
];
```
The code above is an Array containing different MultiTweens for separate animations. Notice how prop2 isn't used in the second MultiTween, whereas pro3 isn't used in the first one.

```
CustomAnimation(
    key: ..,
    control: CustomAnimationControl.PLAY_FROM_START,
    tween: animations[X],
    duration: animations[X].duration,
    ..
)
```
Here you see the CustomAnimation widget that is passed the animation (updated based on the state).
The problem is that, to access the values from within the builder function, I need to access them with .get:

```
   ..
   builder: (_, __, animationValues) {
      double property1 = animationValues.get(AniProp.prop1);
      double property2 = animationValues.get(AniProp.prop2);
      double property2 = animationValues.get(AniProp.prop3);
      ...
   }
```
When I access them from within the builder, since not all of them are specified on every single MultiTween (nor I plan to), I currently get an error, generated from line 132 of your multi_tween.dart:
`    assert(_tracks.containsKey(property),
        "Property '${property.toString()}' does not exists.");`

I understand that this is not a common usage for MultiTweens and that it might be better off this way for others, and I know that Dart is moving away from null. But this to me looks like a situation in which returning 'null' whenever a parameter isn't defined would help, as one could just go with .get(..) ?? X.

That would be the cleanest solution imho and that's why I thought I'd report this issue.
If you don't want to return a null value, you could at least expose a way to use the .containsKey() method, which is currently only available on the private _tracks value.

Current solutions I found (they still work, but they aren't as neat, which prompted me to post this):
1)adding each and every parameter to each MultiTween
2)Using a try-catch (I went for this one right now):
```
try {
   property1 = animationValues.get(AniProp.prop1); //predeclared elsewhere
} catch (_) {}
```
Problem with this solution is that having to try-catch a bunch of stuff isn't neat, and since any of them might fail I have to do them in separate try-catches, one for each. Not sure about performance of this solution but it should be alright.

Let me know what you think of this, and thanks for your support.

**Comment by felixblaschke** [comment]
Thank you for your examples. I found out that you use the same builder but have different properties animated, depending on the MultiTrack used.

I could think about a `animationValue.getOrElse(AniProp.prop1, 200.0)` function. Instead of throwing it will return a specified default value. This way will get around the nullability.

Would that solves your issue?

**Comment by nicoroy2561** [comment]
Yes! That would actually be perfect.

**Comment by felixblaschke** [comment]
I added this function. You can use it with simple animations `2.2.3`. Can you please confirm that it's working as intended?

**Comment by nicoroy2561** [comment]
It works perfectly, thank you very much for your constant support!
This is by far the best animation library for Flutter :)
