### ISSUE TITLE
Icons do not adjust to tween props on Container

### ISSUE THREAD

**Issue by maares** [felixblaschke/simple_animations#40]
Hi there, First great plugin made my life easier :D  

I have created a quick shortcut for those animations I use across the APP, in this example a simple hide appBar when scrolling.

```


Widget saHideAppBar({
    Function animationListener,
    CustomAnimationControl controller,
    Widget widget,
    bool hide,
  }) {
    final _tween = MultiTween<AniProps>()
      ..add(
          AniProps.height,
          (_deviceController.getHeightAppBar())
              .tweenTo(_deviceController.getHeightStatusBar()),
          500.milliseconds);


    return CustomAnimation<MultiTweenValues<AniProps>>(
      control: controller,
      animationStatusListener: animationListener,
      tween: _tween,
      duration: _tween.duration,
      child: widget,
      builder: (context, child, value) {
        return Container(
          height: value.get(AniProps.height),
          child: child,
        ); 
      },
    );
  }

```

It works great, does it's job, although, Icons seems not to be listening to the Container Widget Height as they do not shrink with the animation. 

In bellow example you can see text widgets do disappear while Icons do not:

![myVideo](https://user-images.githubusercontent.com/37770669/96407693-3f775b80-11e2-11eb-8b97-503d454c2bf1.gif)

FYI: I'm not sure this is an issue from SA, but maybe someone already came across and have some insights.

**Comment by maares** [comment]
Hi Guys, not an issue with SA, was using flexibleSpace from AppBar, which seems to behave differently. Will need to review on how to solve it. 

Sorry for opening this issue. Thanks!!

**Comment by felixblaschke** [comment]
Thanks for given feedback on the status of your issue.
