### ISSUE TITLE
Simple animation error

### ISSUE THREAD

**Issue by tonmooy** [felixblaschke/simple_animations#43]
i install this version simple_animations: ^2.2.3

and i face some problem how to fix this

![1](https://user-images.githubusercontent.com/64668179/97806370-81de7500-1c85-11eb-9239-cff4a5e59891.png)
![2](https://user-images.githubusercontent.com/64668179/97806374-8440cf00-1c85-11eb-9cb4-5ba618333e70.png)

**Comment by felixblaschke** [comment]
These examples use supercharged package. Look again at the readme. There's a link to that :)
