### ISSUE TITLE
How to get time property in V2?

### ISSUE THREAD

**Issue by NarHakobyan** [felixblaschke/simple_animations#46]
Hi, Currently I have Rendering class, and I am using time argument from builder function, how can use the same approach with v2 LoopAnimation?
```dart
    return Rendering(
      builder: (context, time) {
        return CustomPaint(
          painter: ParticlePainter(particles, time),
        );
      },
```

V2 code

```dart
return LoopAnimation<int>(
      tween: ConstantTween(1),
      builder: (context, child, value) {
        return CustomPaint(
          painter: ParticlePainter(particles, **time**),
        );
      },
    );
```

**Comment by felixblaschke** [comment]
Hi. I've written migration strategies inside the sa_v1_migration package readme:
https://pub.dev/packages/sa_v1_migration#rendering

I used the particle background example to demonstrate it:
https://github.com/felixblaschke/sa_v1_migration/blob/master/example/lib/examples/particle_background.dart

For version 2.x I migrated that example:
https://github.com/felixblaschke/simple_animations/blob/master/simple_animations/example/lib/examples/particle_background.dart

Just take some time to compare both solutions.
