### ISSUE TITLE
How to auto animate widgets in a List endlessly ?

### ISSUE THREAD

**Issue by santhisagar** [felixblaschke/simple_animations#49]
How to auto animate widgets in a List endlessly? 
I have used MirrorAnimation with AnimatedSwitcher as shown below, Is there any better way of doing this?

```
  final List<Widget> body = [
    Widget1(),
    Widget2(),
    Widget3(),
  ];

 MirrorAnimation(
                tween: IntTween(begin: 0, end: 2),
                builder: (context, child, value) {
                  print('value: $value');
                  return AnimatedSwitcher(
                    duration: const Duration(seconds: 2),
                    reverseDuration: const Duration(seconds: 2),
                    child: body[value],
                  );
                },
                duration: Duration(seconds: 30),
                curve: Curves.linear,
              ),
```

**Comment by felixblaschke** [comment]
You are using `MirrorAnimation` as a mechanism of **providing a timer** that changes the `body`-index. It looks fine, I see nothing bad about that. Alternatively you can use a stateful widget and use a `Future.delayed` to increase the `body`-index yourself. This way you would work around MirrorAnimation.

**Comment by santhisagar** [comment]
Thank you for your quick response.
