### ISSUE TITLE
Can i use CustomAnimation also in StatelessWidget ?

### ISSUE THREAD

**Issue by Adidi** [felixblaschke/simple_animations#50]
Lets say i want to control only on one direction of the animation - say show or hide - So i could control it from the widget property of the class from outside: 
```dart
 Loader(show: loading)
```
and in `Loader`:
```dart
 CustomAnimation<MultiTweenValues<AnimProps>>(
        control: show
            ? CustomAnimationControl.PLAY
            : CustomAnimationControl.PLAY_REVERSE,
        tween: _tween,
        curve: Curves.easeOutQuad,
        duration: 300.milliseconds,
        builder: (context, child, value) {
          return Transform.translate(
            offset: Offset(0, value.get(AnimProps.offset)),
            child: Opacity(
              opacity: value.get(AnimProps.opacity),
              child: child,
            ),
          );
        },
        ...
```

is it bad practice cause flutter will create this widget in any `loading` var change ?

**Comment by felixblaschke** [comment]
Hi, it's totally fine. When something updates, Flutter compares the "current Widget tree" with "newly created one". The creation of the widgets tree is the sum of all builder() calls inside your app. 

It will automatically reuse the existing instance of `CustomAnimation`. It will call it's `didUpdateWidget` method notifies it about the changed `control` parameter. This is how Flutter works and really awesome.

For more info about that topic I recommend:
https://www.youtube.com/watch?v=996ZgFRENMs

**Comment by Adidi** [comment]
@felixblaschke  Thanks !

and btw really amazing job with `simple_animations` - I think flutter animation api is awful and your work really makes more sense of it - I wish that they would put it in their core code maybe somewhere in the fututre.

Excellent job man ! kudos 👏👏👏

**Comment by felixblaschke** [comment]
Thanks! I think Flutter devs made a good job providing a low level API, so package creators can build high level APIs on top of that. In CSS (web) for example you can just use the existing CSS properties but can't create new ones, that anyhow influence the rendering. Flutter is very open at this point.

**Comment by Adidi** [comment]
Yee you probably right - maybe its because I am more `functional programming` enthusiastic and come from typescript background I really think OOP can be cumbersome and boilerplaty with all those Object creations for anything. even to make simple POJO class for json you need to use annotation in `dart` and everything seems really verbose.
I think their animation api is indeed low level which is good but there are so many options to do the same thing and this I think is a bit problems in the api designs.
even their navigation api (specially navigation 2) is very very cumbersom - but then again - its a metter of taste i guess.
