### ISSUE TITLE
How can I insert pauses between tweens?

### ISSUE THREAD

**Issue by harkairt** [felixblaschke/simple_animations#51]
The documentation states that staggered animations can be made, and the tool for it would be the `MultiTween`. I haven't found how I could insert delays/puases between the Tweens.

[flutter.dev](https://flutter.dev/docs/development/ui/animations/staggered-animations) defines staggered animation as _visual changes happen as a series of operations, rather than all at once. The animation might be purely sequential, with one change occuring after the next, or it might partially or completely overlap. It **might also have gaps**, where no changes occur._

Scanning through the docs it seems like it is a missing feature, or have I overlooked something?

Thank you!

**Comment by felixblaschke** [comment]
You can utilize Flutter's `ContantTween` for now.

```dart
final _tween = MultiTween<AniProps>()
    ..add(AniProps.width, 0.0.tweenTo(100.0), 1000.milliseconds)
    ..add(AniProps.width, ConstantTween<double>(100.0), 500.milliseconds)
    ..add(AniProps.width, 100.0.tweenTo(200.0), 1000.milliseconds);
```

I am currently working on a more intuitive way to declare pauses. (Sneak preview here: https://www.youtube.com/watch?v=I3Cteon3ih4 )

**Comment by harkairt** [comment]
awesome! thank you! :)
