### ISSUE TITLE
Plasma more than two Colors

### ISSUE THREAD

**Issue by PyFinn** [felixblaschke/simple_animations#53]
Hello,
is there a way to add more than 2 Colors to the 'Plasma' effect?

**Comment by felixblaschke** [comment]
Relates to https://github.com/felixblaschke/simple_animations/issues/48

I am currently working on it.
If you can't wait, use multiple Plasma inside a Stack.

**Comment by PyFinn** [comment]
Thank you. You are doing a great job!

**Comment by felixblaschke** [comment]
Resolved with 2.5.0.
Article with details at https://felixblaschke.medium.com/huge-upgrade-for-your-flutter-animations-98d73ee6a714
