### ISSUE TITLE
The method 'PlasmaRenderer' isn't defined

### ISSUE THREAD

**Issue by amebrahimi** [felixblaschke/simple_animations#55]
Hello, I have exported code from Liquid Studio and There is a class Called `PlasmaRenderer` there is no good suggestion to export it from any library and I couldn't find how to implement the class from the tutorial.

**Comment by felixblaschke** [comment]
You need simple_animations 2.5.0 as dependency.

**Comment by felixblaschke** [comment]
Created related issue: https://github.com/felixblaschke/simple_animations/issues/56

**Comment by amebrahimi** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!
```
And I'm using `simple_animations: ^3.0.0-nullsafety.2` version

**Comment by amebrahimi** [comment]
Even I changed from `simple_animations: ^3.0.0-nullsafety.2` to `simple_animations: ^2.5.0` no luck it doesn't recognizing `PlasmaRender`
my Imports
```
import 'package:flutter/material.dart';
import 'package:supercharged/supercharged.dart';
import 'package:simple_animations/simple_animations.dart';
```

**Comment by felixblaschke** [comment]
There is currently no null-safe port of `2.5.0`. Make sure to use 2.5.0. Try to delete your pubspec lock file.

**Comment by amebrahimi** [comment]
Thank you it solved my problem.

**Comment by felixblaschke** [comment]
I migrated the new version `2.5.0` to nullsafety with version `3.0.0-nullsafety.3`.
https://pub.dev/packages/simple_animations/versions/3.0.0-nullsafety.3
