### ISSUE TITLE
Vanilla Code Example

### ISSUE THREAD

**Issue by esDotDev** [felixblaschke/simple_animations#57]
It's a bit frustrating to find a code example in the readme, that uses an external lib, which then uses extensions which are difficult and annoying to import. 

Would be nice to have a copy and paste example that runs with just this package, before introducing the extensions based syntax. Or bundle supercharged so this example just runs.

**Comment by felixblaschke** [comment]
I started working on that. I will provide a vanilla example beside that supercharged one. I use this as an opportunity to generally improve the code example quality.

**Comment by felixblaschke** [comment]
Done. All examples in the documentation got reworked.
Examples now use less supercharged, and if they use it, there is a non-supercharged alternative version.
Also required imports are now always in examples.
