### ISSUE TITLE
Plasma: visual with lines

### ISSUE THREAD

**Issue by wmla419** [felixblaschke/simple_animations#58]
For the Liquid effect, is it possible to add some straight line effect (lines moving around) ?
Thank you so much!!

**Comment by felixblaschke** [comment]
Can you provide an example (image or video) of what you imagine?
Straight lines can be everything :-)

**Comment by wmla419** [comment]
Some ideas that you may use as reference,
https://codepen.io/jkantner/pen/mqOdoy
https://codepen.io/cr0ybot/pen/zNyYeW

Anyway, really appreciate your work, it looks awesome!

**Comment by felixblaschke** [comment]
Thank you for the examples. These effects looks nice. I will put it on the todo list :-)

**Comment by wmla419** [comment]
Thank you so much, looking forward to your future updates!

**Comment by felixblaschke** [comment]
Liquid feature development is discontinued.
