### ISSUE TITLE
Migrate Rendering to PlayAnimation

### ISSUE THREAD

**Issue by DaVaMa1** [felixblaschke/simple_animations#59]
Hi there,

I'm a bit new to Flutter animations but I'm trying to convert your example from [here](https://felixblaschke.medium.com/particle-animations-with-flutter-756a23dba027) to the new package.

So far I've got everything working user the old Rendering Widget, but I'm having trouble using the new types.

`return Rendering(
      startTime: 10.seconds,
      builder: (BuildContext context, Duration time) {
        _simulateParticles(time);
        return CustomPaint(
          painter: ParticlePainter(particles, time, Paths.hearthPath,
              scalingFactor: .5),
        );
      },
    );`

(I'm also new to markdown and pasting code here...)

I'm guessing I have to use a PlayAnimation? Or am I missing something important? 

Thanks.

**Comment by DaVaMa1** [comment]
And litteraly just after posting this I go over the migration guide again and see the LoopAnimation suggestion... my bad....

**Comment by MirceaX2Mobile** [comment]
@felixblaschke Hello I'm trying to convert Rendering to but how can I fast-forward the animation using LoopAnimation?

**Comment by felixblaschke** [comment]
Rendering basically was like "rebuild on every frame". You can achieve something like this with

```dart
LoopAnimationBuilder(
      builder: (context, _, __) {
        return // rebuild every frame
      },
      tween: Tween(begin: 0, end: 1),
      duration: const Duration(seconds: 1),
    )
```

**Comment by MirceaX2Mobile** [comment]
@felixblaschke Thank you for your answer, I know that. But Im working on a particles animation and I need to go fast forward with 30 seconds in the future like your exemple from Medium, which is not outdate :(.

And I don't have the onTick function anymore to simulate the particles.

**Comment by felixblaschke** [comment]
Here is a solution with an older state of the API: https://github.com/felixblaschke/simple_animations/blob/2.0.0/example/lib/examples/particle_background.dart

Just rename LoopAnimation to LoopAnimationBuilder and adapt to current API if necessary

**Comment by MirceaX2Mobile** [comment]
@felixblaschke Thank you for your help!

**_shuffle()** did the trick, I guess this is the functions that forwards the animation.
