### ISSUE TITLE
Link is not working.

### ISSUE THREAD

**Issue by utkarshshendge** [felixblaschke/simple_animations#60]
Hi,
the link https://github.com/felixblaschke/simple_animations_example_app is used in [Flutter Sample](https://github.com/flutter/samples)  repository. But it looks like simple_animation_example_app  is either shifted to another folder ,deleted or made private.
Please suggest a workaround  so that I can do necessary changes in [Flutter Samples](https://github.com/flutter/samples) repository as my first open-source contribution.

Thanks for making animations easy😊.

**Comment by felixblaschke** [comment]
The example app wasn't up-to-date anymore this is why I removed it.

You can browse it in recent versions: https://github.com/felixblaschke/simple_animations/tree/2.4.2/example
