### ISSUE TITLE
Absent type parameters in timeline API

### ISSUE THREAD

**Issue by shyndman** [felixblaschke/simple_animations#61]
Hi there,

It appears that `TimelineScene.animate` and `TimelineScene.addSubsequentScene` both return a bare `TimelineScene`, rather than `TimelineScene<T>`. As such, Dart sees it as `TimelineScene<dynamic>`, and without a cast the analyzer complains.

**Comment by shyndman** [comment]
I sent a pull your way if you agree that this presents an issue.

Thanks for the package, btw. It's a breath of fresh air. :)

**Comment by felixblaschke** [comment]
Thanks! ... Sure, it's an issue :-) I overlooked it and my analyzer was lazy and didn't said anything :D

I will look into your changes.

**Comment by felixblaschke** [comment]
Resolved with version 2.5.1 / 3.0.0-nullsafety.4

**Comment by shyndman** [comment]
Thank you! 😄
