### ISSUE TITLE
Feature Request for PlayAnimation and CustomAnimation => Visibility on/off on Animation End

### ISSUE THREAD

**Issue by Edorin9** [felixblaschke/simple_animations#63]
```
AnimatedOpacity(
    opacity: widget.isShown ? 1 : 0,
    duration: const Duration(milliseconds: 200),
    curve: Curves.easeIn,
    onEnd: () => setState(() => _isVisible = false),
    child: Visibility(
        visible: _isVisible,
        child: const CircularProgressIndicator(),
    ),
)
```

Maybe add an implementation of "onEnd" from above code for PlayAnimation, but instead of a callback just let it take a boolean. So maybe instead of onEnd, you can name it showOnEnd or hideOnEnd (hideOnEnd sounds more appropriate to me). this would eliminate the need for use of stateful widget on the AnimatedOpacity code above.

I haven't thought much about a possible implementation on CustomAnimation. But what I'm thinking is maybe specify a value range where the child should be hidden. 

EDIT: My code block above uses an AnimatedOpacity and not a PlayAnimation because I have no idea how to do it using PlayAnimation.

**Comment by felixblaschke** [comment]
CustomAnimation exposes `animationStatusListener` property from it's internal `AnimationController` that can be used to listen to animation complete.

```dart
animationStatusListener: (AnimationStatus status) {
      if (status == AnimationStatus.completed)
        setState(() => someBool = false);
    }
```

Also see:
- https://pub.dev/documentation/simple_animations/latest/simple_animations/CustomAnimation-class.html
- https://github.com/felixblaschke/simple_animations/blob/master/example/stateless_animation.md#customanimation-in-stateless-environment

**Comment by felixblaschke** [comment]
Related to https://github.com/felixblaschke/simple_animations/issues/64

**Comment by felixblaschke** [comment]
Feature will come with `4.0.0`. It can be tested in `4.0.0-next.3`.
