### ISSUE TITLE
CustomAnimation Reverse

### ISSUE THREAD

**Issue by thize** [felixblaschke/simple_animations#65]
Hello, I'm a big fan!

Here is my suggestion:

.PLAY_REVERSE should not be 100% equal to .PLAY

CustomAnimation could have:

* reverseDelay
* reverseDuration
* reverseCurve

or just start delay again when change to .PLAY_REVERSE. and with this we can:

```dart
CustomAnimation<double>(
  builder: (c, w, v) => builder(c, w, v),
  tween: Tween<double>(begin: 0, end: 1),
  curve: reversed ? curve1 : curve2,
  delay: reversed ? delay1 : delay2,
  duration: reversed ? duration1 : duration2,
  control: reversed
      ? CustomAnimationControl.PLAY_REVERSE
      : CustomAnimationControl.PLAY,
  child: child,
);
```

**Comment by felixblaschke** [comment]
I'll guess this is a very rare use case. Introducing new properties for the reverse might blow up the API and confuse people.

I'll recommend to do it the way you demonstrated in the code snippet, but without the delay. The delay can be backed in to the tween. You can delay something in the tween by using Interval (Flutter's own) or TimelineTween (simple_animations' high level abstraction)
