### ISSUE TITLE
Code not available 

### ISSUE THREAD

**Issue by aanantt** [felixblaschke/simple_animations#69]
I want to use [Bubble particle system](https://github.com/felixblaschke/simple_animations/blob/master/example/lib/examples/particle_background.dart) in my project but it is not available on github anymore. can you please provide me the source code?
and thank you so much for this awesome package :)

**Comment by felixblaschke** [comment]
You can use the version tag in github-urls to revive older examples:
https://github.com/felixblaschke/simple_animations/blob/2.0.0/example/lib/examples/particle_background.dart

**Comment by aanantt** [comment]
Thank you so much, I got it.

**Comment by aanantt** [comment]
Hey @felixblaschke!!!
Iam have been trying to replace the bubbles circle shape with heart shape but it's been 2 days still I couldn't figure out. 

here is my heart shape code 
```
class HeartShape extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    // TODO: implement paint
   

    Paint paint1 = Paint();
    paint1
      ..color = Colors.red
      ..style = PaintingStyle.fill
      ..strokeWidth = 0;

    double width = size.width;
    double height = size.height;

    Path path = Path();
    path.moveTo(0.5 * width, height * 0.45);
    path.cubicTo(0.3 * width, height * 0.14, -0.25 * width, height * 0.6,
        0.5 * width, height*0.85);
    path.moveTo(0.5 * width, height * 0.45);
    path.cubicTo(0.8 * width, height * 0.15, 1.25 * width, height * 0.6,
        0.5 * width, height*0.85);

    canvas.drawPath(path, paint1);
   }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```
can you please help me out of this??

**Comment by felixblaschke** [comment]
Basically you need to replace this line with another shape: https://github.com/felixblaschke/simple_animations/blob/2.0.0/example/lib/examples/particle_background.dart#L121

Sorry, but I don't have the time to focus on beginner Flutter questions. You can reach out to flutterhelp-subreddit as they are more beginner focused: https://www.reddit.com/r/flutterhelp/
