### ISSUE TITLE
Problem with params builder of CustomAnimation

### ISSUE THREAD

**Issue by ERICAntoine** [felixblaschke/simple_animations#75]
Hi,

I am in the process of passing my application to null safety but I don't know how to convert this and i have this error:

The method 'get' isn't defined for the type 'Object'.
Try correcting the name to the name of an existing method, or defining a method named 'get'.dart(undefined_method)

![Capture d’écran 2021-06-05 à 16 38 57](https://user-images.githubusercontent.com/35992294/120897122-8c4a5e00-c61c-11eb-8bfd-9f69dd4c3a4f.png)

Thanks for your help

**Comment by felixblaschke** [comment]
CustomAnimation (alike PlayAnimation or MirrorAnimation) use generic to specify the type of the animated value.

If you are animating for example a `double` value you need to instance the CustomAnimation class like this:

```dart
return CustomAnimation<double>(...);
```
Dart will use this type to infer the correct type for `value` in the `builder()`.

The documentation also includes examples: https://github.com/felixblaschke/simple_animations/blob/master/doc/stateless_animation.md#customanimation

**Comment by felixblaschke** [comment]
It looks like you are using `TimelineTween` or it's processor `MultiTween`.

Here you can find examples for that: 
- https://github.com/felixblaschke/simple_animations/blob/master/example/timeline_tween.md
- https://github.com/felixblaschke/simple_animations/blob/master/doc/multi_tween.md#examples

**Comment by ERICAntoine** [comment]
Thanks ;)
