### ISSUE TITLE
Is it possible to make this animation with this package ? 

### ISSUE THREAD

**Issue by kalismeras61** [felixblaschke/simple_animations#80]
Hello I have been trying to make below animation. I tried couple of package but they didn't help me. Is it possible make this with this package ? 

What i want to do : https://www.youtube.com/watch?v=N_qv3HskOLY&feature=youtu.be

If you give an example i will be grateful.

**Comment by felixblaschke** [comment]
The TimelineTween can be useful for your examples. You can do a staggered animation by using 3 different properties.

Examples: https://github.com/felixblaschke/simple_animations/blob/master/example/timeline_tween.md

If you need help for your implementation, you might also refer to https://www.reddit.com/r/flutterhelp/
