### ISSUE TITLE
Can we add some delay between scene ? 

### ISSUE THREAD

**Issue by kalismeras61** [felixblaschke/simple_animations#81]
I want to add some delay between to scene. For example first animatin will start and will wait same position with some delay and scond animation(sceene) will start. How can i do that ?

**Comment by felixblaschke** [comment]
You can use the TimelineTween to add the delay inside the tween.

Look at the code from the flutterplasma demo, where I time certains steps in my animation:
https://github.com/felixblaschke/flutterplasma/blob/master/lib/demo/intro/intro.dart#L139
