### ISSUE TITLE
min sdk 2.14 because of unwaited

### ISSUE THREAD

**Issue by hardikvij195** [felixblaschke/simple_animations#82]
Hi, I'm facing this issue while running a simple fade animation and its throwing me this issue.

 ../../FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/simple_animations-4.0.0/lib/stateless_animation/custom_animation.dart:199:7: Error: The method 'unawaited' isn't defined for the class '_CustomAnimationState<T>'.
     - '_CustomAnimationState' is from 'package:simple_animations/stateless_animation/custom_animation.dart' ('../../FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/simple_animations-4.0.0/lib/stateless_animation/custom_animation.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'unawaited'.
          unawaited(aniController.reverse(from: 1.0));

Thanks In Advance

**Comment by hardikvij195** [comment]
Fixed by upgrading flutter

**Comment by felixblaschke** [comment]
Not your problem. My fault. I mistakenly didn't raised the mind SDK version to 2.14. I used new `unawaited` method from 2.14 dart sdk.

**Comment by felixblaschke** [comment]
resolved with version `4.0.1`

**Comment by felixblaschke** [comment]
@hardikvij195 Thank you for reporting this bug :)
