### ISSUE TITLE
How to create Wave animation style with Latest Version ??/

### ISSUE THREAD

**Issue by tonyhart7** [felixblaschke/simple_animations#85]
so I wondering from your post on medium but I cant recreate that because its look life the package has changes drastically
would be good if you can told me quick look or tips on to recreate wave animation like you have from medium

**Comment by felixblaschke** [comment]
Maybe this already helps: https://github.com/felixblaschke/simple_animations/issues/74

**Comment by tonyhart7** [comment]
Yeah already done the animation wave via looking from change logs 

the problem is MultiTween but I guess is fixed now
