### ISSUE TITLE
MultiTween

### ISSUE THREAD

**Issue by jinfagang** [felixblaschke/simple_animations#86]
how to migrate?

<img width="616" alt="image" src="https://user-images.githubusercontent.com/21303438/158012290-08f78d40-4bff-4888-b9f1-756bd31859ae.png">

**Comment by felixblaschke** [comment]
Hi. MultiTween hasn't changed and should be working with recent version of simple animation. But it looks like you are using it differently then expected.

Here are the docs: https://github.com/felixblaschke/simple_animations/blob/2.5.1/example/multi_tween.md

But if you are refactoring this tween, I'll recommend to use TimelineTween: https://github.com/felixblaschke/simple_animations#timeline-tween-guide

**Comment by felixblaschke** [comment]
Oh I now saw you came from very "old" MultiTrackTween. Then go use TimelineTween tween 😀

**Comment by jinfagang** [comment]
thanks, I just finished and made it work. I hope the APIs in simple_animation won't changes a lot in the future so that my app can stay with current code
