### ISSUE TITLE
Syncing animations between different widgets/screens

### ISSUE THREAD

**Issue by mwawrusch** [felixblaschke/simple_animations#90]
We are using an animated gradient and I would like to keep the background consistent between changes of the screen. Technically each screen has it's own background widget so I'd need to sync the start time for the MirrorAnimation and direction with a global timer / state. What's the best way to achieve this?

**Comment by felixblaschke** [comment]
Sorry my response seems to not made it. I was pointing out that you can use the current time and use modulo operator to divide by a duration. That will make all widgets sync on a global level.
