### ISSUE TITLE
How to implement a GPS Playback Animation

### ISSUE THREAD

**Issue by drexhacker** [felixblaschke/simple_animations#93]
I have managed to implement live location animation in my app using google maps and looping through the given GPS Positions updating the marker's position though am I want also to create a **GPS Playback Animation** with a playback control like for media so that I can play, pause, resume, seek and reverse the animation. Thank You for any help!

**Comment by felixblaschke** [comment]
You can use an AnimationController and set the value to control the progress manually and connect it to a slider UI. I made something similar here for the dev tools: https://github.com/felixblaschke/simple_animations/blob/main/lib/animation_developer_tools/animation_developer_tools.dart

**Comment by drexhacker** [comment]
Thanks For the Tip, it actually worked so simply, I had spent days troubling my self. Thanks A lot!
