### ISSUE TITLE
Docs for Plasma Renderer

### ISSUE THREAD

**Issue by charlieforward9** [felixblaschke/simple_animations#95]
I am using code from a demo that depends on this package. It has not been updated in 2 years so the version is clearly older. I opened an issue on the demo repo for context. felixblaschke/flutterplasma#11

I could not figure out how to solve the unrecognized PlasmaRenderer error due to insufficient [changelog documentation](https://pub.dev/packages/simple_animations/changelog), so I had to opt to downgrade my version to 3.0.3.

I am looking for some help with keeping the plugin version updated without compromising the functionality. See the referenced issue for context!

Thank you for your open-source contributions!

**Comment by charlieforward9** [comment]
Finally realizing that these repo's are managed by the same person, lol!

**Comment by felixblaschke** [comment]
As stated in changelog (https://github.com/felixblaschke/simple_animations/blob/main/CHANGELOG.md#400) with 4.x the Liquid/Plasma feature got extracted into an own package: https://pub.dev/packages/sa3_liquid

I won't add any new features to it, but you can use in the state as it currently is.
