### ISSUE TITLE
Animate the same property twice within one scene (or within one animation) doesn't work

### ISSUE THREAD

**Issue by WieFel** [felixblaschke/simple_animations#97]
Hi,

I am trying to animate the color of a text, first from normal text color (black) to red (within the interval `0.0` to `0.1`), then again from red back to normal text color (interval `0.9` to `1.0`).
The animation from `0.0` to `0.1` works fine. But the second animation is somehow just ignored, and lets the color jump as if there was no animation.
```dart
enum AnimatedColor { color }

...

_textAnimation = MovieTween()
  .scene(begin: Duration.zero, end: controller.duration)
  .tween(
    AnimatedColor.color,
    ColorTween(begin: Colors.black, end: Colors.red),
    curve: const Interval(0.0, 0.1, curve: Curves.linear),
  )
  .tween(
    AnimatedColor.color,
    ColorTween(begin: Colors.red, end: Colors.black),
    curve: const Interval(0.9, 1.0, curve: Curves.linear),
  )
  .parent
  .animatedBy(controller);

...

@override
Widget build(BuildContext context) {
  return AnimatedBuilder(
    animation: _textAnimation,
    builder: (context, child) => Text(
      "Hello World",
      style: TextStyle(color: _textAnimation.value.get(AnimatedColor.color)),
    ),
  );
}
```

When I use two animated properties `AnimatedColor.color1` and `AnimatedColor.color2`, I can get it to work by using `Color.lerp(_textAnimation.value.get(AnimatedColor.color1), _textAnimation.value.get(AnimatedColor.color2), controller.value)`. But I don't think the sense of using animations is to manually call `Color.lerp()`!?

Am I missing anything here?

**Comment by felixblaschke** [comment]
Hey, I think this example does (despite other things) what you trying to achieve:
https://pub.dev/packages/simple_animations/example#complex-example

**Comment by WieFel** [comment]
Thanks!

It now works, using two separate scenes, and using the scene's start/end instead of the curve `Interval` that I used before.

```dart
(MovieTween()
  ..scene(
    begin: Duration.zero,
    duration: const Duration(seconds: 1),
  ).tween(
    ...,
    curve: Curves.linear,
  )
  ..scene(
    begin: Duration(seconds: 4),
    duration: const Duration(seconds: 1),
  ).tween(
    ...,
    curve: Curves.linear,
  )
  .parent)
.animatedBy(controller)
```
