### ISSUE TITLE
Timer from "startDelay" is not cancelled when the animation is disposed

### ISSUE THREAD

**Issue by joaosilva2095** [felixblaschke/simple_animations#99]
Hello everyone,

During my automated testing, I observed that the tests were failing because of an unexpected "Timer" that remained active even after the test had completed. Upon investigating the code in "simple_animations," I discovered that when we set a "startDelay," a Timer is created but not cancelled during on dispose. Consequently, the Timer continues running even after the widget has been disposed.

This situation leads to test failures and potentially unwanted animations being executed. I propose the idea of introducing a Timer variable and cancelling it when the widget is unmounted. What are your thoughts on this approach?

https://github.com/felixblaschke/simple_animations/blob/8356606b2c85982dc920ab55439fc8e8f50391ec/lib/animation_builder/custom_animation_builder.dart#LL169C1-L169C48

**Comment by felixblaschke** [comment]
Hi, that is a good hint. I made the implementation as suggested for `5.0.1`. Can you please try if it solves your issue? 😄

**Comment by joaosilva2095** [comment]
It does @felixblaschke, fantastic work 🙌
